### ISSUE TITLE
ask for advice in agcrn.py

### ISSUE THREAD

**Issue by ningque-t** [liuxu77/STGCL#1]
output = output[:, -1:, :, :]  # (B, 1, N, D)
At the bottom of agcrn.py, why only the last of second dimension of the output sequence is taken

**Comment by liuxu77** [comment]
Hi, because the output variable stores all the output states of RNN, and we only need to use the last state of RNN as the summary of the input time series.

**Comment by ningque-t** [comment]
> Hi, because the output variable stores all the output states of RNN, and we only need to use the last state of RNN as the summary of the input time series.

Sincerely thank you for your reply
