### ISSUE TITLE
Wondering if you will release the Bay data and relevant scripts

### ISSUE THREAD

**Issue by jsun57** [liuxu77/STGCL#2]

**Comment by jsun57** [comment]
Also, is it possible to share other baselines? Thanks a lot.

**Comment by liuxu77** [comment]
Hi, sorry for the late reply.

The bay dataset is available at the DCRNN repository (https://github.com/liyaguang/DCRNN). Specifically, the pems-bay.h5 file can be downloaded here: https://drive.google.com/drive/folders/10FOTa6HXPqX8Pf5WRoRwcFnW9BrNZEIX

The adjacency matrix file adj_mx_bay.pkl is provided here: https://github.com/liyaguang/DCRNN/blob/master/data/sensor_graph

Thanks.
