### ISSUE TITLE
file missing 

### ISSUE THREAD

**Issue by PEIYUNHUA** [liuxu77/STGCL#3]
Hi, could you provide the file for 'args.traffic_df_filename', without this file it shows the error in gen_data.py, line 34, df = pd.read_hdf(args.traffic_df_filename). Many thanks!

**Comment by PEIYUNHUA** [comment]
need to set it as 'PEMS0x.csv'

**Comment by liuxu77** [comment]
Hi, sorry for the typo, but I think this script should read the pems-0x.h5 file instead of .csv. Thanks.
